# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d37fcd5740b1c09fa57e62d879ab27d5"
name = "events-management"
application_url = "https://displayed-pad-theory-passenger.trycloudflare.com/"
embedded = true
handle = "events-management"

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_content,write_products,write_files"

[auth]
redirect_urls = [
  "https://displayed-pad-theory-passenger.trycloudflare.com/auth/callback",
  "https://displayed-pad-theory-passenger.trycloudflare.com/auth/shopify/callback",
  "https://displayed-pad-theory-passenger.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
